import { USER_AGENT } from "../src/version.ts";

const PREAMBLE = `// generated by scripts/gen-constants.ts, do not edit
import type { LiteralUnion } from "./types.ts";

export type Medium = LiteralUnion<"TVA" | "극장판" | "OVA" | "기타">;
export type RatingType = LiteralUnion<"방송통신심의위원회" | "영상물등급위원회">;
export type RatingComponent = LiteralUnion<"선정성" | "주제" | "폭력성" | "모방위험" | "대사" | "공포" | "약물">;

`;

async function get(path: string): Promise<Record<string, unknown>> {
  const res = await fetch("https://api.laftel.net/api/" + path, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) throw new Error(`${path} -> ${res.status}`);
  return await res.json();
}

function union(name: string, values: unknown): string {
  if (!Array.isArray(values) || values.length === 0) throw new Error(`empty union: ${name}`);
  const uniq = [...new Set(values.map(String))].sort();
  const lines: string[] = [];
  for (let i = 0; i < uniq.length; i += 4) {
    lines.push("  | " + uniq.slice(i, i + 4).map((v) => JSON.stringify(v)).join(" | "));
  }
  return `export type ${name} = LiteralUnion<\n${lines.join("\n")}\n>;\n\n`;
}

const info = await get("v1.0/info/discover/");
const banned = await get("users/v1/banned_words/");

let out = PREAMBLE;
out += union("Genre", info.genres);
out += union("Brand", info.brands);
out += union("Tag", info.tags);
out += union("Production", info.productions);
out += union("AnimeYear", (info.years as { animation?: unknown })?.animation);
out += union("BannedWord", banned.banned_word_list);

const { writeFile } = await import("node:fs/promises");
await writeFile(new URL("../src/constants.ts", import.meta.url), out);
console.log("wrote src/constants.ts");
